//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR5
{
    using System;
    using System.Collections.Generic;
    
    public partial class StatusTicket
    {
        public int ID_StatusTicket { get; set; }
        public string Status { get; set; }
        public int TicketOrdersID { get; set; }
    
        public virtual TicketOrders TicketOrders { get; set; }
    }
}
