//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PR5
{
    using System;
    using System.Collections.Generic;
    
    public partial class TicketOrders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TicketOrders()
        {
            this.Payments = new HashSet<Payments>();
            this.StatusTicket = new HashSet<StatusTicket>();
        }
    
        public int ID_TicketOrders { get; set; }
        public int SessionID { get; set; }
        public Nullable<int> TicketPrice { get; set; }
        public int SnackOrdersID { get; set; }
        public Nullable<int> TicketCount { get; set; }
        public string DateTimeBroni { get; set; }
        public string StatusBooking { get; set; }
        public string PhoneNumber { get; set; }
        public string FirstName { get; set; }
        public int WorkerID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payments> Payments { get; set; }
        public virtual Sessions Sessions { get; set; }
        public virtual SnackOrders SnackOrders { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusTicket> StatusTicket { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
